// Generated by `wit-bindgen` 0.29.0. DO NOT EDIT!
// <auto-generated />
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace SpinHttpWorld {

    public interface ISpinHttpWorld {
    }

    public readonly struct None {}

    [StructLayout(LayoutKind.Sequential)]
    public readonly struct Result<Ok, Err>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<Ok, Err> ok(Ok ok)
        {
            return new Result<Ok, Err>(OK, ok!);
        }

        public static Result<Ok, Err> err(Err err)
        {
            return new Result<Ok, Err>(ERR, err!);
        }

        public bool IsOk => Tag == OK;
        public bool IsErr => Tag == ERR;

        public Ok AsOk
        {
            get
            {
                if (Tag == OK)
                return (Ok)value;
                else
                throw new ArgumentException("expected OK, got " + Tag);
            }
        }

        public Err AsErr
        {
            get
            {
                if (Tag == ERR)
                return (Err)value;
                else
                throw new ArgumentException("expected ERR, got " + Tag);
            }
        }

        public const byte OK = 0;
        public const byte ERR = 1;
    }

    public class Option<T> {
        private static Option<T> none = new ();

        private Option()
        {
            HasValue = false;
        }

        public Option(T v)
        {
            HasValue = true;
            Value = v;
        }

        public static Option<T> None => none;

        [MemberNotNullWhen(true, nameof(Value))]
        public bool HasValue { get; }

        public T? Value { get; }
    }

    public static class InteropString
    {
        internal static IntPtr FromString(string input, out int length)
        {
            var utf8Bytes = Encoding.UTF8.GetBytes(input);
            length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            return gcHandle.AddrOfPinnedObject();
        }
    }

    public class WitException: Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }

    namespace exports {
        public static class SpinHttpWorld
        {
        }
    }

}
