spin_manifest_version = 2

[application]
name = "grpc"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[[trigger.http]]
route = "/..."
component = "grpc"

[component.grpc]
source = "build/App.wasm"
[component.grpc.build]
command = "dotnet publish -o build App.csproj"
